<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="shakthi" failures="3" tests="3" name="com.partycity.runner.TestRunner" time="26.544" errors="0" timestamp="2023-05-31T16:20:16 IST" skipped="0">
  <testcase classname="com.partycity.runner.TestRunner" name="runScenario" time="10.215">
    <failure message="expected [https://www.partycity.com/account?registration=false] but found [https://www.partycity.com/account-login]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.partycity.com/account?registration=false] but found [https://www.partycity.com/account-login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.partycity.stepDefinition.LoginPageTestSteps.i_should_be_redirected_to_the_account_page(LoginPageTestSteps.java:65)
at ✽.I should be redirected to the account page "https://www.partycity.com/account?registration=false"(file:///C:/Users/shakt/git/PartyCity/src/test/resources/feature/account-login.feature:15)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.partycity.runner.TestRunner" name="runScenario" time="5.623">
    <failure message="expected [We&#039;re sorry, there is an error with your email and/or password. Please try again] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [We're sorry, there is an error with your email and/or password. Please try again] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.partycity.stepDefinition.LoginPageTestSteps.i_should_see_an_error_message_indicating_the_login_failed(LoginPageTestSteps.java:45)
at ✽.I should see an error message indicating the login failed "We're sorry, there is an error with your email and/or password. Please try again"(file:///C:/Users/shakt/git/PartyCity/src/test/resources/feature/account-login.feature:27)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.partycity.runner.TestRunner" name="runScenario" time="10.706">
    <failure message="expected [https://www.partycity.com] but found [https://www.partycity.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.partycity.com] but found [https://www.partycity.com/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.partycity.stepDefinition.AccountPageTestSteps.i_should_be_logged_out_and_redirected_to_the_home_page(AccountPageTestSteps.java:43)
at ✽.I should be logged out and redirected to the "https://www.partycity.com" Home page(file:///C:/Users/shakt/git/PartyCity/src/test/resources/feature/account-login.feature:20)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- com.partycity.runner.TestRunner -->
